### ISSUE TITLE
EXTRA_ROUTE_SETTINGS is global for every server

### ISSUE THREAD

**Issue by kakawait** [docker/dockercloud-haproxy#113]
Using following `docker-compose.yml`

```
version: '2'
services:
  blue:
    image: dockercloud/hello-world
    environment:
      - "EXTRA_ROUTE_SETTINGS=weight 1"
  green:
    image: dockercloud/hello-world
    environment:
      - "EXTRA_ROUTE_SETTINGS=weight 2"
  lb:
    image: dockercloud/haproxy
    links:
      - blue
      - green
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80
```

I may expect something like

```
backend default_service
  server test_blue_1 test_blue_1:80 check inter 2000 rise 2 fall 3 weight 1
  server test_green_1 test_green_1:80 check inter 2000 rise 2 fall 3 weight 2
```

but actual result is

```
backend default_service
  server test_blue_1 test_blue_1:80 check inter 2000 rise 2 fall 3 weight 2
  server test_green_1 test_green_1:80 check inter 2000 rise 2 fall 3 weight 2
```
