### ISSUE TITLE
Redirect 80 -> 443 and forward 443 to 8080

### ISSUE THREAD

**Issue by anaibol** [docker/dockercloud-haproxy#125]
My webapp container exposes port 8080 and an api port 3030.

Dockercloud/haproxy container should listen to port 443 and 80 (-> 443).

I am using Stackfiles and I've been redirecting the path `/api` with `VIRTUAL_HOST=*/api/*`.

Adding SSL support, I am not sure if I have to replace line breaks on the `DEFAULT_SSL_CERT` param.
For the http -> https redirect I am using the `FORCE_SSL` param.

What config should I use for the forward? I am on the right way with this config?

`````` api:
  autoredeploy: true
  environment:
    - "VIRTUAL_HOST=*/api/*"
    - "VIRTUAL_HOST_WEIGHT=1"
    - "FORCE_SSL=yes"
  image: "anaibol/webapp-api:latest"
web:
  autoredeploy: true
  environment:
    - "VIRTUAL_HOST=*"
    - "VIRTUAL_HOST_WEIGHT=0"
    - "FORCE_SSL=yes"
  image: "anaibol/webapp:latest"
  links:
    - api
lb:
  image: "dockercloud/haproxy:latest"
  links:
    - api
    - web
  ports:
    - "443:443"
    - "80:80"
  roles:
    - global
  environment:
    - "DEFAULT_SSL_CERT=-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"```
``````

**Comment by tifayuki** [comment]
@anaibol 
1) to set CERT via environment variable, you have to replace the "\n"(line break) with "\" and "\n"
2) to redirect http to https, besides setting FORCE_SSL, you have to set both http and https hosts on your app container. e.g.`VIRTUAL_HOST=http://your.domain, https://your.domain`. In you case, it should be `VIRTUAL_HOST=http://*/api/*, https://*/api/*`

**Comment by robertavram** [comment]
I'm also struggling with this - can't get it to work... individually i can access both services.. as soon as i try to route them i can't get it to work:
```
haproxy-dev:
  deployment_strategy: every_node
  environment:
    - "DEFAULT_SSL_CERT=-----BEGIN PRIVATE KEY-----\\n blah blah \\n-----END CERTIFICATE-----\\n"
  expose:
    - '1936'
  image: 'dockercloud/haproxy:1.6.0'
  links:
    - pmp-dev
    - web-dev
  ports:
    - '80:80'
    - '443:443'
  restart: always
  roles:
    - global
  tags:
    - dev
pmp-dev:
  command: http-server -a 0.0.0.0 -p 8080 /code/build/pmp/bundled
  environment:
    - FORCE_SSL=yes
    - 'VIRTUAL_HOST=https://etools-dev.unicef.org/pmp/*, http://etools-dev.unicef.org/pmp/*'
    - VIRTUAL_HOST_WEIGHT=1
  expose:
    - '8080'
  image: 'unicef/etools-pmp:develop'
  tags:
    - dev
redis-dev:
  image: 'redis:latest'
  tags:
    - dev
web-dev:
  command: 'newrelic-admin run-program gunicorn EquiTrack.wsgi -b "0.0.0.0:8080" -w 4 --timeout=3200 --log-level debug'
  environment:
   
    - FORCE_SSL=yes
    - 'VIRTUAL_HOST=*'
    - VIRTUAL_HOST_WEIGHT=0
  expose:
    - '8080'
  image: 'unicef/etools:develop'
  links:
    - redis-dev
  tags:
    - dev
```
