### ISSUE TITLE
Unable to load balance a service that uses net: host when roles: - global is set

### ISSUE THREAD

**Issue by derekdon** [docker/dockercloud-haproxy#132]
This might not be an issue and is perhaps just a lack of docker networking understanding... but I'm unable to load balance a service that uses net: host when the load balancer service is given roles: - global. The load balancer works as expected with roles global in place for all services that use net: bridge, but is only able to resolve services that use net: host when the roles: - global flag is removed. Any ideas what's happening here?

Doesn't work:
```
web:
  deployment_strategy: high_availability
  target_num_containers: 3
  image: 'someimage:latest'
  net: host
  ports:
    - '4984:4984'
    - '4985:4985'
  restart: on-failure
  tags:
    - web
  volumes:
    - '/tmp:/tmp/config'
loadbalancer:
  deployment_strategy: high_availability
  target_num_containers: 1
  image: 'dockercloud/haproxy:1.6.0'
  links:
    - web
  net: bridge
  ports:
    - '80:80'
    - '443:443'
  restart: always
  roles:
    - global
  tags:
    - loadbalancer
```

Works with global role removed:
```
web:
  deployment_strategy: high_availability
  target_num_containers: 3
  image: 'someimage:latest'
  net: host
  ports:
    - '4984:4984'
    - '4985:4985'
  restart: on-failure
  tags:
    - web
  volumes:
    - '/tmp:/tmp/config'
loadbalancer:
  deployment_strategy: high_availability
  target_num_containers: 1
  image: 'dockercloud/haproxy:1.6.0'
  links:
    - web
  net: bridge
  ports:
    - '80:80'
    - '443:443'
  restart: always
  tags:
    - loadbalancer
```

Works with global role present but linked service is using net: bridge:
```
web:
  deployment_strategy: high_availability
  target_num_containers: 3
  image: 'someimage:latest'
  net: bridge
  ports:
    - '4984:4984'
    - '4985:4985'
  restart: on-failure
  tags:
    - web
  volumes:
    - '/tmp:/tmp/config'
loadbalancer:
  deployment_strategy: high_availability
  target_num_containers: 1
  image: 'dockercloud/haproxy:1.6.0'
  links:
    - web
  net: bridge
  ports:
    - '80:80'
    - '443:443'
  restart: always
  roles:
    - global
  tags:
    - loadbalancer
```

Just to point out that two containers share the web node and they communicate on localhost so net: host is being used.
