### ISSUE TITLE
real ip, forwarded for etc?

### ISSUE THREAD

**Issue by derekdon** [docker/dockercloud-haproxy#134]
I'm having trouble applying the env variables required to provide the details of the server being used to service the request to the header information. I'd like to have something like this taken from my old nginx config.

```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
Stackfile:
```
loadbalancer:
  deployment_strategy: high_availability
  environment:
    - BALANCE=roundrobin
    - MAXCONN=4096
    - MODE=http
    - 'TIMEOUT=connect 5000,client 50000,server 500000'
  image: 'dockercloud/haproxy:1.6.0'
  links:
    - syncgateway
  ports:
    - '80:80'
    - '443:443'
    - '1936:1936'
  restart: always
  roles:
    - global
  tags:
    - loadbalancer
```

I'm load balancing my syncgateway service's 4984 port. The above stackfile works but when I start adding EXTRA_FRONTEND_SETTINGS_80 or OPTIONS etc, it usually stops working.

Any pointers on how I can achieve this?
