### ISSUE TITLE
Session stickiness with `COOKIE` seems not working

### ISSUE THREAD

**Issue by micha149** [docker/dockercloud-haproxy#14]
I try to configure session stickiness with the `COOKIE` variable. I added it to my docker compose file as follows:
```
    lb:
        image: dockercloud/haproxy
        links:
            - web
        environment:
          - COOKIE=SRV insert indirect nocache
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 80:80
```

This is the configuration from the docker logs:

```
lb_1    | global
lb_1    |   log 127.0.0.1 local0
lb_1    |   log 127.0.0.1 local1 notice
lb_1    |   log-send-hostname
lb_1    |   maxconn 4096
lb_1    |   pidfile /var/run/haproxy.pid
lb_1    |   user haproxy
lb_1    |   group haproxy
lb_1    |   daemon
lb_1    |   stats socket /var/run/haproxy.stats level admin
lb_1    |   ssl-default-bind-options no-sslv3
lb_1    |   ssl-default-bind-ciphers --- I removed this ---
lb_1    | defaults
lb_1    |   balance roundrobin
lb_1    |   log global
lb_1    |   mode http
lb_1    |   option redispatch
lb_1    |   option httplog
lb_1    |   option dontlognull
lb_1    |   option forwardfor
lb_1    |   timeout connect 5000
lb_1    |   timeout client 50000
lb_1    |   timeout server 50000
lb_1    | listen stats
lb_1    |   bind :1936
lb_1    |   mode http
lb_1    |   stats enable
lb_1    |   timeout connect 10s
lb_1    |   timeout client 1m
lb_1    |   timeout server 1m
lb_1    |   stats hide-version
lb_1    |   stats realm Haproxy\ Statistics
lb_1    |   stats uri /
lb_1    |   stats auth stats:stats
lb_1    | frontend default_frontend
lb_1    |   bind :80
lb_1    |   maxconn 4096
lb_1    |   default_backend default_service
lb_1    | backend default_service
lb_1    |   server dockertest_web_1 dockertest_web_1:3000 check
```

If I understand haproxy and the config script correctly, there should be a `cookie` in the backends server lines… Do I anything wrong? Is it a bug?
