### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by Quentinvarquet** [docker/dockercloud-haproxy#142]
Hello, I have an issue when I am trying to use your LB container.

I found it on a blog ( https://www.brianchristner.io/how-to-scale-a-docker-container-with-docker-compose/ ). When I am using the docker-compose files on the website I don't have any problem. Here is the docker-compose.yml file : 

```
version: '2'
services:
  web:
    image: dockercloud/hello-world
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis
    links:
      - web
    networks:
      - back-tier

  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - web
    networks:
      - front-tier
      - back-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
```

If I go **http://ip_of_y_server** I can see the page, I can udate it 150 times I will never have any problem.

I just updated the **docker-compose.yml** file to use an apache image : 

```
version: '2'
services:
  web:
    image: eboraas/apache
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis
    links:
      - web
    networks:
      - back-tier

  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - web
    networks:
      - front-tier
      - back-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
```

When I go again on **http://ip_of_my_server**, I have the apache default page, but sometimes when I update it (just with F5) I have an error (about port 443). But If I update it again, then it works.

> Bad Request
> 
> Your browser sent a request that this server could not understand.
> Reason: You're speaking plain HTTP to an SSL-enabled server port.
> Instead use the HTTPS scheme to access this URL, please.
> Apache/2.4.10 (Debian) Server at 172.22.0.2 Port 443

![image](https://cloud.githubusercontent.com/assets/7962157/20972041/e640eec0-bc93-11e6-9311-2bce7c92f7b0.png)

Everytime I use an apache or nginx container I have this problem...

You can try it here (this is a temporary server from scaleway) : http://163.172.168.63/

Thank you

**Comment by tifayuki** [comment]
My guess is the image you are using (`eboraas/apache`) exposes two ports, one is plain tcp and the other is TLS. You incoming request is dispatched to the two ports  in round robin, and this is the reason you see 4xx error.

To fix this, simply add `EXCLUD_PORTS=443` to your web app.

**Comment by Quentinvarquet** [comment]
Hello,

I tried to update the Dockerfile, I deleted : 

> EXPOSE 443

Everything works, I don't have the bad request anymore, thank you !


Do you know if-is possible to add  ``` EXCLUD_PORTS=443``` somewhere directly in the docker-compose.yml file ? 

Thank you :-)

**Comment by tifayuki** [comment]
add as an environment variable: 
```
web:
    image: eboraas/apache
    networks:
      - front-tier
      - back-tier
    environment:
      - EXCLUDE_PORTS=443
```
