### ISSUE TITLE
exposing internal network ports

### ISSUE THREAD

**Issue by pasupulaphani** [docker/dockercloud-haproxy#146]
```
version: '2'
services:
  proxy-local:
    image: 'dockercloud/haproxy:1.5.3'
    environment:
      VIRTUAL_HOST: **
      SSL_CERT: ****
    links:
      - shell-local
    ports:
      - 8080:443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  elasticsearch-local:
    image: 'elasticsearch:5.1-alpine'
    ports:
      - 9200:9200
```

I can see that localhost:9200 is reachable from my host machine. Correct me if I'm wrong, shouldn't it be only available to internal network?

**Comment by tifayuki** [comment]
```
 elasticsearch-local:
    image: 'elasticsearch:5.1-alpine'
    ports:
      - 9200:9200
```

You publish the port `9200` in the compose file, that is why you can access it from your local machine
