### ISSUE TITLE
very unreliable

### ISSUE THREAD

**Issue by thebigredgeek** [docker/dockercloud-haproxy#149]
stackfile:

```yaml
graphql-worker-blue:
  autodestroy: always
  deployment_strategy: high_availability
  environment:
    - AWS_USER_FILE_ACCESS_KEY_ID=xxxxxxxx
    - AWS_USER_FILE_ACL=public-read
    - AWS_USER_FILE_BUCKET=jobstart-app
    - 'AWS_USER_FILE_CLOUDFRONT_FQDN=https://d2ohg34tzu17vf.cloudfront.net'
    - AWS_USER_FILE_REGION=us-west-2
    - AWS_USER_FILE_SECRET_ACCESS_KEY=xxxxxxxxxx
    - 'DEBUG=graphql:*'
    - GOOGLE_PLACES_API_KEY=xxxxxxxx
    - JWT_SECRET=xxxxxxxxxxx
    - NODE_ENV=production
    - PORT=80
    - 'POSTGRES_URL=postgres://xxxxx:xxxxxxxx@aws-us-east-1-portal.9.dblayer.com:16390/jobstart'
    - 'REDIS_URL=redis://x:xxxxxxxxx@aws-us-east-1-portal.11.dblayer.com:27350'
    - SENDGRID_API_KEY=xxxxxx
  expose:
    - '80'
  image: 'jobstartinc/graphql:latest'
  mem_limit: 2048m
  ports:
    - '80:80'
  restart: on-failure
  tags:
    - application
  target_num_containers: 2
lb:
  environment:
    - "DEFAULT_SSL_CERT=-----BEGIN RSA PRIVATE KEY-----xxxx-----END RSA PRIVATE KEY-----\\n-----BEGIN CERTIFICATE-----xxxx\\n-----END CERTIFICATE-----\\n"
  image: 'dockercloud/haproxy:1.6.1'
  links:
    - graphql-worker-blue
  ports:
    - '80:80'
    - '443:443'
  restart: always
  roles:
    - global
  tags:
    - loadbalancer
```

Endpoints:

<img width="1101" alt="screen shot 2016-12-15 at 2 21 15 pm" src="https://cloud.githubusercontent.com/assets/2799276/21244288/c4ef8d14-c2d1-11e6-8ca4-56a3005efe80.png">

Notice that graphql-worker-blue's [service url](http://graphql-worker-blue.graphql.4a25bab8.svc.dockerapp.io/health) works but lb's [service url](http://lb.graphql.d6a74d97.svc.dockerapp.io/health) does not.

Log output from HAProxy:

```bash
[lb-1]2016-12-15T22:18:35.288664694Z INFO:haproxy:dockercloud/haproxy 1.6.1 has access to the Docker Cloud API - will reload list of backends  in real-time
[lb-1]2016-12-15T22:18:35.289002128Z INFO:haproxy:dockercloud/haproxy PID: 5
[lb-1]2016-12-15T22:18:35.440078260Z INFO:haproxy:=> Add task: Websocket open
[lb-1]2016-12-15T22:18:36.440837973Z INFO:haproxy:=> Executing task: Websocket open
[lb-1]2016-12-15T22:18:36.441051049Z INFO:haproxy:==========BEGIN==========
[lb-1]2016-12-15T22:18:37.055881687Z INFO:haproxy:Linked service: GRAPHQL_WORKER_BLUE(4a25bab8-022b-41e3-866b-c32c68aae521)
[lb-1]2016-12-15T22:18:37.056073644Z INFO:haproxy:Linked container: GRAPHQL_WORKER_BLUE_1(86d52dea-73f2-4595-aa1c-178317454991), GRAPHQL_WORKER_BLUE_2(e0fe6319-d576-40c2-aff9-26dfba96594e)
[lb-1]2016-12-15T22:18:37.056960536Z INFO:haproxy:SSL certificates are updated
[lb-1]2016-12-15T22:18:37.057528440Z INFO:haproxy:HAProxy configuration:
[lb-1]2016-12-15T22:18:37.057538390Z global
[lb-1]2016-12-15T22:18:37.057541413Z   log 127.0.0.1 local0
[lb-1]2016-12-15T22:18:37.057544045Z   log 127.0.0.1 local1 notice
[lb-1]2016-12-15T22:18:37.057546455Z   log-send-hostname
[lb-1]2016-12-15T22:18:37.057549363Z   maxconn 4096
[lb-1]2016-12-15T22:18:37.057551758Z   pidfile /var/run/haproxy.pid
[lb-1]2016-12-15T22:18:37.057554193Z   user haproxy
[lb-1]2016-12-15T22:18:37.057556572Z   group haproxy
[lb-1]2016-12-15T22:18:37.057558835Z   daemon
[lb-1]2016-12-15T22:18:37.057561456Z   stats socket /var/run/haproxy.stats level admin
[lb-1]2016-12-15T22:18:37.057563956Z   ssl-default-bind-options no-sslv3
[lb-1]2016-12-15T22:18:37.057568113Z   ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:DHE-DSS-AES128-SHA:DES-CBC3-SHA
[lb-1]2016-12-15T22:18:37.057572552Z defaults
[lb-1]2016-12-15T22:18:37.057574910Z   balance roundrobin
[lb-1]2016-12-15T22:18:37.057577267Z   log global
[lb-1]2016-12-15T22:18:37.057579610Z   mode http
[lb-1]2016-12-15T22:18:37.057581898Z   option redispatch
[lb-1]2016-12-15T22:18:37.057584337Z   option httplog
[lb-1]2016-12-15T22:18:37.057586674Z   option dontlognull
[lb-1]2016-12-15T22:18:37.057589057Z   option forwardfor
[lb-1]2016-12-15T22:18:37.057591307Z   timeout connect 5000
[lb-1]2016-12-15T22:18:37.057593587Z   timeout client 50000
[lb-1]2016-12-15T22:18:37.057595854Z   timeout server 50000
[lb-1]2016-12-15T22:18:37.057598085Z listen stats
[lb-1]2016-12-15T22:18:37.057600627Z   bind :1936
[lb-1]2016-12-15T22:18:37.057602862Z   mode http
[lb-1]2016-12-15T22:18:37.057609785Z   stats enable
[lb-1]2016-12-15T22:18:37.057612069Z   timeout connect 10s
[lb-1]2016-12-15T22:18:37.057618864Z   timeout client 1m
[lb-1]2016-12-15T22:18:37.057621407Z   timeout server 1m
[lb-1]2016-12-15T22:18:37.057623652Z   stats hide-version
[lb-1]2016-12-15T22:18:37.057626035Z   stats realm Haproxy\ Statistics
[lb-1]2016-12-15T22:18:37.057628462Z   stats uri /
[lb-1]2016-12-15T22:18:37.057630696Z   stats auth stats:stats
[lb-1]2016-12-15T22:18:37.057632977Z frontend default_port_80
[lb-1]2016-12-15T22:18:37.057635247Z   bind :80
[lb-1]2016-12-15T22:18:37.057637494Z   reqadd X-Forwarded-Proto:\ http
[lb-1]2016-12-15T22:18:37.057639904Z   maxconn 4096
[lb-1]2016-12-15T22:18:37.057642241Z   default_backend default_service
[lb-1]2016-12-15T22:18:37.057644554Z frontend default_port_443
[lb-1]2016-12-15T22:18:37.057646864Z   bind :443 ssl crt /certs/
[lb-1]2016-12-15T22:18:37.057656777Z   reqadd X-Forwarded-Proto:\ https
[lb-1]2016-12-15T22:18:37.057660032Z   maxconn 4096
[lb-1]2016-12-15T22:18:37.057662388Z   default_backend default_service
[lb-1]2016-12-15T22:18:37.057664671Z backend default_service
[lb-1]2016-12-15T22:18:37.057667081Z   server GRAPHQL_WORKER_BLUE_1 10.7.0.13:80 check inter 2000 rise 2 fall 3
[lb-1]2016-12-15T22:18:37.057669661Z   server GRAPHQL_WORKER_BLUE_2 10.7.0.14:80 check inter 2000 rise 2 fall 3
[lb-1]2016-12-15T22:18:37.057864030Z INFO:haproxy:Launching HAProxy
[lb-1]2016-12-15T22:18:37.060353096Z INFO:haproxy:HAProxy has been launched(PID: 13)
[lb-1]2016-12-15T22:18:37.060455277Z INFO:haproxy:===========END===========
```

I've cycled the stack about 50 times at this point.  Sometimes it randomly works, only to stop working the next cycle, regardless of how long I wait after startup.  Sometimes the error is "cannot reach", othertimes it's a 503.  Really frustrating, as part of the appeal of using docker cloud is not having to worry about manual configuration for stuff like this.  I've tried 1.5.3 and 1.6.1.  This didn't used to be an issue with docker cloud.  Seems to have started a few months ago, with stuff getting more and more unstable

Any help here would be appreciated.  My company is unfortunately about ready to move out 15+ node stack off of docker cloud and over to google compute or regular old AWS ECS.
