### ISSUE TITLE
Exclude matching path from VIRTUAL_HOST

### ISSUE THREAD

**Issue by santiagopoli** [docker/dockercloud-haproxy#173]
Hi,

I have a swarm cluster with a service (service1) listening on port 8080 and a dockercloud-haproxy listening on port 80.

I've added the **VIRTUAL_HOST** variable in the service1 configuration (VIRTUAL_HOST=*/service1). 

The problem I'm facing is that the proxy is redirecting requests in the form of 
_**{ examplehost/service1 -> examplehost:8080/service1 }**_,
 but **I want to achieve** something like 
**_{ examplehost/service1 -> examplehost:8080 }_**

I assume this MUST be possible, because I think is the most common use case. For example I'm creating a service that uses the **bargenson/docker-swarm-visualizer** image, and I want to have access to it by doing something like http://myhost.com/visualizer rather than http://myhost.com:8080

The relevant part in the docker-compose.yml for this scenario is:

```
version: '3'

services:

  lb:
    image: dockercloud/haproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.role == manager
         
  dashboard:
    image: bargenson/docker-swarm-visualizer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8080:8080'
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=*/dashboard
      - SERVICE_PORTS=8080
    deploy:
      placement:
        constraints:
          - node.role == manager


[...]
```

Thanks in advance!
