### ISSUE TITLE
Proxy for TCP services in swarm mode (docker 1.13)

### ISSUE THREAD

**Issue by shuston** [docker/dockercloud-haproxy#179]
I'm having trouble getting this to work - it may be my understanding of how to set it up.

What I want to have is:
- haproxy listen on tcp port 16000 (NOT a web service - TCP mode)
- forward to docker services attached to same docker network
- the services (there are 4 in my test case) all listen on TCP port 8000

The behavior I see is that the TCP connection into port 16000 is accepted, then the remote client sends the first protocol bytes and the connection is reset/closed. Nothing ever happens on port 8000.

I set this up in a docker stack compose and have tweaked the service settings since, but what I have is:

```
services:
  my-lb:
    image: dockercloud/haproxy:latest
    ports:
      - 16000:16000
    networks:
      - my-net
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # (There are 4 of these, only one shown)
  my-service1:
    image: repo:5000/my-service1:1.0-1
    networks:
      - my-other-other-net
      - my-other-net
      - my-net
    deploy:
      placement:
        constraints: [node.role == worker]
    environment:
      - SERVICE_PORTS="8000"
      - TCP_PORTS="8000"
```
