### ISSUE TITLE
Scale the Load Balance

### ISSUE THREAD

**Issue by alexsandro-xpt** [docker/dockercloud-haproxy#199]
Could I scale the docker cloud haproxy load balance for I can get High Availability? I can't find nothing about that in the documentantion.

Is this a good practice?

**Comment by tifayuki** [comment]
Yes. The only limitation is that you can only scale the haproxy to swarm mangers, if you are using the swarm mode. Then, the swarm internal LB will do the load balancing in each haproxy containers.

If you are using docker cloud standard mode, the service endpoint provided by docker cloud uses a DNS round robin to resolve to different haproxy containers.

**Comment by alexsandro-xpt** [comment]
@tifayuki I'm using Swarm Mode with `Docker For Azure`, and `Docker For AWS` and deploy the dockercloud-haproxy with `docker stack deploy`, take look at my docker-compose.yml below:

```
  docker-cloud-proxy:
    image: dockercloud/haproxy
    ports:
      - 80:80
      - 443:443
      - 1936:1936
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
```

See, I'm scalling dockercloud-haproxy with `replicas: 2` command. Is it right?
