### ISSUE TITLE
haproxy stuck in restart loop

### ISSUE THREAD

**Issue by cmberard** [docker/dockercloud-haproxy#200]
So I've scoured the interwebs, but cannot seem to find a resolution to this issue. Haproxy is intermittently getting stuck in a restart loop. I've tried version 1.6.2 and 1.6.5, but getting the same result. Only way I've found to resolve the issue is to restart the loadbalancer service, and then everything is fine for an hour or so. Any help/suggestions would be greatly appreciated!

Haproxy version: 1.6.2 & 1.6.5

Console Output:

```
[lb-1]2017-05-16T21:49:46.247250059Z INFO:haproxy:=> Executing task: haproxy 15 died , restart
[lb-1]2017-05-16T21:49:46.247282860Z INFO:haproxy:==========BEGIN==========
[lb-1]2017-05-16T21:49:50.246575792Z INFO:haproxy:=> Add task: haproxy 15 died , restart
[lb-1]2017-05-16T21:49:55.247779119Z INFO:haproxy:=> Add task: haproxy 15 died , restart
[lb-1]2017-05-16T21:50:00.249218454Z INFO:haproxy:=> Add task: haproxy 15 died , restart
[lb-1]2017-05-16T21:50:05.250185375Z INFO:haproxy:=> Add task: haproxy 15 died , restart
[lb-1]2017-05-16T21:50:10.250702184Z INFO:haproxy:=> Add task: haproxy 15 died , restart
```

Relevant Stackfile:

```
lb:
  image: 'dockercloud/haproxy:1.6.5'
  links:
    - service-1
    - service-2
    - service-3
  ports:
    - '80:80'
    - '443:443'
  restart: on-failure
  roles:
    - global
```
