### ISSUE TITLE
Swarm service deploy mode = global is not supported

### ISSUE THREAD

**Issue by blop** [docker/dockercloud-haproxy#240]
When using service in swarm, dockercloud/haproxy fails to link backend for services deployed globally.
```
    serviceA:
        deploy:
            mode: global
```

 Workaround is to switch to replicated deploy mode (which is the default).
```
    serviceA:
        deploy:
            mode: replicated
            replicas: 3
```

It seems the containers created for globally deployed services are named differently, with a 0 as the second part of the name instead of the node id.

This should be fixed, and/or a warning should be added in the documentation if not.
