### ISSUE TITLE
imcompatible with docker compose 1.23

### ISSUE THREAD

**Issue by DeoLeung** [docker/dockercloud-haproxy#248]
seems the container naming schema changed, which may be the cause that it can't find the containers

**Comment by DeoLeung** [comment]
I roll compose back to 1.22.0 and it works

**Comment by rubenfonseca** [comment]
Took me a while to figure out why it wasn't working. I can confirm the new naming schema breaks the image.

**Comment by jorihardman** [comment]
A workaround is to use `container_name` to change the name of your linked container back to what haproxy expects.

Example from my compose file:

```yaml
services:
  rails:
    container_name: rails_server_rails_1
   ...

  haproxy:
    links:
      - rails
    ...
```

That fixed it for me in 1.23.1
