### ISSUE TITLE
Service redeploy results in 503 error

### ISSUE THREAD

**Issue by Starefossen** [docker/dockercloud-haproxy#4]
Whenever a service linked to HAProxy is redeployed I end up with 503 errors when attempting to access the virtual host for service after a successful redeploy of the service. This is the console output I have for a redeploy from HAProxy:

```
proxy-1 | 2016-02-17T12:32:58.066607490Z INFO:haproxy:==========BEGIN==========
proxy-1 | 2016-02-17T12:32:58.068433250Z INFO:haproxy:Event: container e2bd1288-2f7b-46c7-8075-f3d44b03d46b is terminated
proxy-1 | 2016-02-17T12:32:59.377172101Z INFO:haproxy:Service links: APP(035cb9a5-4dd9-42fe-9280-21dc8e8be22f)
proxy-1 | 2016-02-17T12:32:59.379267548Z INFO:haproxy:Container links: APP_1(1e391941-79ed-447a-a556-30387bba8997)
proxy-1 | 2016-02-17T12:32:59.386043240Z INFO:haproxy:HAProxy configuration remains unchanged
proxy-1 | 2016-02-17T12:32:59.386848017Z INFO:haproxy:===========END===========
proxy-1 | 2016-02-17T12:32:59.390035142Z INFO:haproxy:==========BEGIN==========
proxy-1 | 2016-02-17T12:32:59.390889239Z INFO:haproxy:Event: container 1e391941-79ed-447a-a556-30387bba8997 is running
proxy-1 | 2016-02-17T12:33:00.099824069Z INFO:haproxy:Service links: APP(035cb9a5-4dd9-42fe-9280-21dc8e8be22f)
proxy-1 | 2016-02-17T12:33:00.101004643Z INFO:haproxy:Container links: APP_1(1e391941-79ed-447a-a556-30387bba8997)
proxy-1 | 2016-02-17T12:33:00.107965332Z INFO:haproxy:HAProxy configuration remains unchanged
proxy-1 | 2016-02-17T12:33:00.108892125Z INFO:haproxy:===========END===========
```

**Comment by fermayo** [comment]
It seems that the redeploy was too fast and when haproxy tried to reload the configuration nothing changed (because the new container had the same configuration and the same IP).
Did the 503 disappear after a while, or it didn't? Did you try to redeploy haproxy? Did that fix the issue?

**Comment by Starefossen** [comment]
The issue disappears by it self after a minute. I have redeployed HAProxy multiple times on all tags available without any change in this behavior.

 It looks like I have mitigated this by having two instances of every service with sequential deploy.

**Comment by revett** [comment]
Running into this issue.

**Comment by tifayuki** [comment]
@revett 
Does the haproxy configuration not update when you added the service, or it updates but you get a 503 error?

**Comment by samuelgiles** [comment]
I've just had it happen upon a redeploy, HAProxy stats says 'Layer4 connection problem: Connection refused' which results in a 503. The container log doesn't indicate any problem and seems to read the same as every other time a service is redeployed.

**Comment by revett** [comment]
@tifayuki this causes the 503 error:

```yaml
ha-proxy:
  image: 'dockercloud/haproxy:1.2.1'
  deployment_strategy: every_node
  links:
    - hq
    - platform
  ports:
    - '80:80'
  restart: always
  roles:
    - global
  tags:
    - staging
    - platform

hq:
  image: 'dockercloud/hello-world:latest'
  environment:
    - VIRTUAL_HOST=hq.staging.example.co
  expose:
    - '80'
  restart: always
  tags:
    - staging
    - platform
  target_num_containers: 1

platform:
  image: 'dockercloud/hello-world:latest'
  environment:
    - VIRTUAL_HOST=app.staging.example.co
  expose:
    - '80'
  restart: always
  tags:
    - staging
    - platform
  target_num_containers: 1
```

### Any ideas?

-----

This `stack.yml` will successfully route requests from both subdomains (`hq.` + `app.`) to the two different services as expected:

```yaml
ha-proxy:
  image: 'dockercloud/haproxy:1.2.1'
  deployment_strategy: every_node
  links:
    - hq
    - platform
  ports:
    - '80:80'
  restart: always
  roles:
    - global
  tags:
    - staging
    - platform

hq:
  image: 'dockercloud/hello-world:latest'
  expose:
    - '80'
  restart: always
  tags:
    - staging
    - platform
  target_num_containers: 1

platform:
  image: 'dockercloud/hello-world:latest'
  expose:
    - '80'
  restart: always
  tags:
    - staging
    - platform
  target_num_containers: 1
``` 

How is `VIRTUAL_HOST` breaking it?

**Comment by rafagsiqueira** [comment]
Exactly same problem here.

**Comment by paulinder** [comment]
Hmm... It's not clear to me whether my issue fits here, or is separate, but here goes..

My `docker-compose.yml` looks like below. Under this configuration, I get `503` for everything.

```
  lb:
    image: dockercloud/haproxy
    links:
      - entities
      - sentiment
      - topics
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    volumes:
      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
    ports:
      - 8080:80

  entities:
    extends:
      file: common.yml
      service: microservice
    build:
      context: services/entities/
    environment:
      - VIRTUAL_HOST="*/entities, */entities/*"
    command: "python main.py"

  sentiment:
    extends:
      file: common.yml
      service: microservice
    build:
      context: services/sentiment/
    environment:
      - VIRTUAL_HOST="*/sentiment, */sentiment/*"
    command: "python main.py"

  topics:
    extends:
      file: common.yml
      service: microservice
    build:
      context: services/topics/
    environment:
      - VIRTUAL_HOST="*/topics, */topics/*"
    command: "python main.py"
```

If I remove the `VIRTUAL_HOST` for each service, I can query the haproxy server at / (with no path) and it cycles between each service in a round-robin style.

Any ideas?

**Comment by paulinder** [comment]
Hmm... I think I may have solved it. I think it was due to incorrect `VIRTUAL_HOST` format... Here is my *.yml with working service direction:

```
  lb:
    image: dockercloud/haproxy
    links:
      - entities
      - sentiment
      - topics
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    volumes:
      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
    ports:
      - 8080:80

  entities:
    extends:
      file: common.yml
      service: microservice
    build:
      context: services/entities/
    environment:
      - 'VIRTUAL_HOST=*/entities, */entities/*'
    command: "python main.py"

  sentiment:
    extends:
      file: common.yml
      service: microservice
    build:
      context: services/sentiment/
    environment:
      - 'VIRTUAL_HOST=*/sentiment, */sentiment/*'
    command: "python main.py"

  topics:
    extends:
      file: common.yml
      service: microservice
    build:
      context: services/topics/
    environment:
      - 'VIRTUAL_HOST=*/topics, */topics/*'
    command: "python main.py"
```
