### ISSUE TITLE
Q: How to map container ports to virtual host ports?

### ISSUE THREAD

**Issue by Bekt** [docker/dockercloud-haproxy#55]
Maybe I'm missing something, but it seems like it is not possible to bind exposed ports to virtual host ports. 

```
web:
  image: myimage
  autoredeploy: true
  expose:
    - '4000'
    - '5000'
  environment:
    - VIRTUAL_HOST='example.com:4444, example.com:5555'
```

How can I expose container port `4000` at `example.com:4444` and container port `5000` at `example.com:5555`?

**Comment by tifayuki** [comment]
@Bekt 
You don't have to expose any ports on your application containers. Instead, you need to expose and publish the ports on haproxy container.

**Comment by Bekt** [comment]
Hi @tifayuki, yeah that is what I am asking. The `expose` property here is:

>Expose ports without publishing them to the host machine - they’ll only be accessible to linked services. Only the internal port can be specified.


Anyway, the container internally exposes (not to the host) the two ports above. How can I tell haproxy to bind them to ports? More specific example:

```
app1:
  image: app1
  expose:
    - '4000' # I want haproxy to proxy port 4444 to this container port (4000)
    - '5000' # I want haproxy to proxy port 5555 to this container port (5000)
  environment:
    - VIRTUAL_HOST='example.com:4444, example.com:5555'

app2:
  image: app1
  expose:
    - '4000' # I want haproxy to proxy port 6666 to this container port (4000)
    - '5000' # I want haproxy to proxy port 7777 to this container port (5000)
  environment:
    - VIRTUAL_HOST='example.com:6666, example.com:7777'

lb:
  image: dockercloud/haproxy
  links:
    - app1
    - app2
  ports:
    - 4444:4444
    - 5555:5555
    - 6666:6666
    - 7777:7777
```

Unfortunately, haproxy performs a roundrobin scheduling to one of the container ports. Instead, I need haproxy to proxy port `4444` to `app1:4000`, `5555` to `app1:5000`, `6666` to `app2:4000`, and `7777` to `app2:5000`.
