### ISSUE TITLE
Migrated to Docker for Mac - now haproxy refuses connections 

### ISSUE THREAD

**Issue by peterlauri** [docker/dockercloud-haproxy#57]
Before I migrated to the Docker for Mac beta, I was using the normal setup for docker on my mac, by using docker-machine etc. The below was a working configuration (sample configuration with just nginx plain service).

```
version: '2'
services:
  web:
    image: nginx:latest
  lb:
    image: dockercloud/haproxy:latest
    links:
      - web
    ports:
      - "80:80"
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    volumes:
      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
```

But when using Docker for Mac Beta, one shouldn't need to set the environment variables and mount the certificate path, as it should be native. So I tried this one:

```
version: '2'
services:
  web:
    image: nginx:latest
  lb:
    image: dockercloud/haproxy:latest
    links:
      - web
    ports:
      - "80:80"
```

I cannot access **localhost** on port 80. If I remove the lb service, and map 80:80 on the web service, then I can access it on localhost as per documentation from Docker for Mac.

This might be a bug in Docker for Mac, but I want to raise this issue here as well, as it might be a combination of them together?

**Comment by peterlauri** [comment]
Sorry, found the problem just after posting. It is stated in the README :) The following configuration works like a charm...

```
version: '2'
services:
  web:
    image: nginx:latest
  lb:
    image: dockercloud/haproxy:latest
    links:
      - web
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
