### ISSUE TITLE
container_name option support

### ISSUE THREAD

**Issue by den-t** [docker/dockercloud-haproxy#59]
Looks like the proxy doesn't pick up containers with non-standard names.
Let's take a sample from the Readme and add one line:
```YAML
version: '2'
services:
  web:
    image: dockercloud/hello-world
    container_name: web
  lb:
    image: dockercloud/haproxy
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
```
It results in
```
lb_1   | INFO:haproxy:Initial start
lb_1   | INFO:haproxy:Linked service: 
lb_1   | INFO:haproxy:Linked container: 
```
Expected
```
lb_1   | INFO:haproxy:Initial start
lb_1   | INFO:haproxy:Linked service: <dirname>_web
lb_1   | INFO:haproxy:Linked container: web
```

It's not necessarily needs to be supported. Just a note in the Readme to not use named containers should suffice.
