### ISSUE TITLE
How to use backup option?

### ISSUE THREAD

**Issue by gomap-us** [docker/dockercloud-haproxy#70]
I am trying to setup automatic failover where I have a container that can take over only if health checks on all other containers fail.

The backup option seems perfect for this : http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#5.2-backup.  However, I am unable to get it to work.

I have tried the following:

- HEALTH_CHECK=check inter 2000 fall 3 rise 2 backup
[Results in all linked containers running as backup even ones without this env var, so they all get used.  Occasionally results in only one service being balanced so it looks like things are working, but is not reliable.]

- EXTRA_SETTINGS=backup
[haproxy fails to start on redeploy]

- OPTION=backup
[No effect?]

Any suggestions? Here is the stackfile I am using (uses two different nodes so I can test failover by powering the primary one off):

```
superproxytest-live:
  image: 'dockercloud/hello-world:latest'
  target_num_containers: 1
  environment:
    - NAME=Live
    - HEALTH_CHECK=check inter 2000 fall 3 rise 2
    - VIRTUAL_HOST=http://superproxytest.superproxytest.6eb2f65c.svc.dockerapp.io
  expose:
    - '80'
  restart: always
  tags:
    - superproxytest_live
superproxytest-replica:
  image: 'dockercloud/hello-world:latest'
  target_num_containers: 1
  environment:
    - NAME=Replica
    # Causes this service AND the live service to be backup
    - HEALTH_CHECK=check inter 2000 fall 3 rise 2 backup
    # Causes HA proxy to fail on re-deploy
    # - EXTRA_SETTINGS=backup
    # Does nothing?
    # - OPTION=backup
    - VIRTUAL_HOST=http://superproxytest.superproxytest.6eb2f65c.svc.dockerapp.io
  expose:
    - '80'
  restart: always
  tags:
    - superproxytest_replica
superproxytest:
  image: dockercloud/haproxy:latest
  deployment_strategy: every_node
  tags:
    - superproxytest
  restart: always
  roles:
    - global
  ports:
    - "80:80"
    - "1936:1936"
  environment:
     - STATS_AUTH=stats:stats
  links:
    - "superproxytest-live:superproxytest-live"
    - "superproxytest-replica:superproxytest-replica"
```

**Comment by tifayuki** [comment]
In a services , all the containers are treated equally. You cannot set some containers are with a backup option while others are not. 

What you can do is to create another service for backup purpose, and set the one you want to backup with `EXTRA_SETTINGS=server backup BACKUP_SERVICE:PORT backup`

**Comment by gomap-us** [comment]
Thanks for the feedback @tifayuki !  After digging around in a couple of the python scripts I found the _merge_services_with_same_vhost function which was indeed causing my backup service to get merged with my primary service.  To get around this I added a fake entry into my backup's VIRTUAL_HOST so the services wouldn't get merged, and then made use of the EXTRA_SETTINGS variable you suggested (but it only worked right if I added it to the primary service in the stackfile).  Also had to throw in some VIRTUAL_HOST_WEIGHT entries to make sure the primary service was used over the backup service when both were available.  Still need to do a bit more testing, but this stackfile appears to be working well on docker cloud so far.

```
proxytest-web:
  image: 'dockercloud/hello-world:latest'
  target_num_containers: 1
  environment:
    - NAME=Live
    - EXTRA_SETTINGS=server Replica proxytest-web-failover:80 backup check
    - VIRTUAL_HOST=http://full_endpoint.domain.for_proxy_service_goes_here.svc.dockerapp.io
    - VIRTUAL_HOST_WEIGHT=10
  expose:
    - '80'
  restart: always
  tags:
    - proxytest_live
proxytest-web-failover:
  image: 'dockercloud/hello-world:latest'
  target_num_containers: 1
  environment:
    - NAME=Replica
    - VIRTUAL_HOST=http://full_endpoint.domain.for_proxy_service_goes_here.svc.dockerapp.io,http://www.trickhaproxyintogroupingthisintoitsownservice.com
    - VIRTUAL_HOST_WEIGHT=1
  expose:
    - '80'
  restart: always
  tags:
    - proxytest_replica
proxytest:
  image: dockercloud/haproxy:latest
  deployment_strategy: every_node
  tags:
    - proxytest
  restart: always
  roles:
    - global
  ports:
    - "80:80"
    - "1936:1936"
  environment:
     - STATS_AUTH=stats:stats
  links:
    - proxytest-web-failover
    - proxytest-web
```
