### ISSUE TITLE
Using links with docker swarm

### ISSUE THREAD

**Issue by Pedramrn** [docker/dockercloud-haproxy#73]
This is my `docker-compose.yml`

``` yml
version: '2'
services:
  app:
    image: pedramrn/webapp:0.1.4
    expose:
      - 8080
    networks:
      - main
    working_dir: /src
    restart: never
    depends_on:
      - db-postgresql

  lb:
    image: dockercloud/haproxy:1.5
    depends_on:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - main
    links:
      - app


  db-postgresql:
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - data-postgresql:/var/lib/postgresql/data
    networks:
      - main
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres


volumes:
  data-postgresql:

networks:
  main:

```

With this configuration docker swarm schedules all the `app` containers on the same node as the  `haproxy` is in, If I remove the `links: -app` then the `haproxy` can't recognize it and does not route any traffic to the containers.

Am I missing something?
