### ISSUE TITLE
using haproxy on another port

### ISSUE THREAD

**Issue by smiffy6969** [docker/dockercloud-haproxy#77]
Say you want to run haproxy on port 8080 maybe becuase you want to run multiple dev environments, I have found that when doing this with tutum or dockercloud version that once you map ha's backend port 80 to another front end port, your virtual host mappings are screwed up, 503 responce.

If you change your virtual host mapping to just * everything is fine, but try and put in something meaningfull like a host mapped local address and it will not have it unless the front end port is on 80 too. I would assume this is due to how the backends are being built into a config file and how ports are being sniffed when writing it.

I have found a work around though...

this is bad

```yml
web1:
  image: tutum/hello-world
  container_name: web1
  environment:
    - 'VIRTUAL_HOST=haproxy.local'
haproxy:
  image: 'dockercloud/haproxy'
  container_name: haproxy
  environment:
    - 'STATS_AUTH=stats:stats'
  links:
    - web1
  ports:
    - "8080:80"
    - "1936:1936"
``` 

this is good

```yml
web1:
  image: tutum/hello-world
  container_name: web1
  environment:
    - 'VIRTUAL_HOST=haproxy.local*'
haproxy:
  image: 'dockercloud/haproxy'
  container_name: haproxy
  environment:
    - 'STATS_AUTH=stats:stats'
  links:
    - web1
  ports:
    - "8080:80"
    - "1936:1936"
```

adding star to the end works fine and lets me have haproxy mapped to 8080 local. This issue is verifed on ubuntu 16.04 and mac (not sure version), 503 response without the star at the end of the virtual host.

Now I am not changing haproxys backend port, so this should not be an issue unless, if you take the hack into account to get around it, the way the server mappings are being written to config on creation of the container have a bug.

ta
