### ISSUE TITLE
VIRTUAL_HOST for multiple nodejs apps

### ISSUE THREAD

**Issue by Triggi** [docker/dockercloud-haproxy#8]
Hi,

What am I missing or not understanding?

When using the VIRTUAL_HOST option with a single nodejs app everything works as expected. I add the path, expose port on container and all requests get routed to the correct nodejs container.
However, the moment I try with several nodejs apps with different ports, only the first gets routed, the rest fail with a 404 error. Routing to a simple nginx site + nodejs app does seem to work.
I've tried everything from setting BACKEND_PORTS, FRONTEND_PORTS, TCP_PORTS, VIRTUAL_HOST_WEIGHT without success though. 

Example config:
```
api-browser:
  image: 'trigdev/api-browser:0.1'
  deployment_strategy: high_availability
  environment:
    - 'APP_PORT= 3013'
    - 'VIRTUAL_HOST=DOMAIN.COMt:80/api/v0/trigg/browse/'
    - VIRTUAL_HOST_WEIGHT=1
  expose:
    - '3013'
  links:
    - amq
    - db
  restart: on-failure
  tags:
    - backend
    - medium
api-crud:
  image: 'trigdev/api-crud:0.1'
  deployment_strategy: high_availability
  environment:
    - 'APP_PORT= 3005'
    - 'VIRTUAL_HOST=DOMAIN.COM:80/api/v0/trigg/'
    - VIRTUAL_HOST_WEIGHT=1
  expose:
    - '3005'
  links:
    - amq
    - db
  restart: on-failure
  tags:
    - backend
    - medium
lb:
  image: 'dockercloud/haproxy:1.0.1'
  deployment_strategy: high_availability
  environment:
    - 'BACKEND_PORTS=3005,3009,3010'
    - BALANCE=roundrobin
  links:
    - api-browser
    - api-crud
    - confirm-email
    - password-reset
  ports:
    - '80:80'
    - '1936:1936'
  restart: on-failure
  roles:
    - global
  tags:
    - frontend
```
