### ISSUE TITLE
Balancing SMTP in Swarm

### ISSUE THREAD

**Issue by gelin** [docker/dockercloud-haproxy#83]
`docker-compose.yml` looks like this:
```
version: '2'
services:
  server:
    image: ...
    expose:
      - '25'
    networks:
      - balancer

  lb:
    image: dockercloud/haproxy
    links:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '9000:25'
      - '8080:1936'
    networks:
      - balancer

networks:
  balancer:
    driver: bridge
```

When I deploy on single Docker I get this haproxy config:
```
...
listen port_25
  bind :25
  mode tcp
  server project_server_1 project_server_1:25 check-send-proxy check inter 10s
```

To deploy to Swarm I remove `docker.sock` volume and add `DOCKER_HOST` environment variable for `lb` container and change network driver to 'overlay'.
The resulting haproxy config:
```
...
frontend default_port_80
  bind :80
  reqadd X-Forwarded-Proto:\ http
  maxconn 4096
  default_backend default_service
backend default_service
  server project_server_1 project_server_1:25 check inter 2000 rise 2 fall 3
```
It keeps the default listening of port 80 and doesn't balance SMTP correctly.

Why the configs are so different for standalone Docker and Swarm?
