### ISSUE TITLE
Random behavior of responding with 502 Bad Gateway 

### ISSUE THREAD

**Issue by ilaif** [docker/dockercloud-haproxy#84]
Hey guys,

I'm experiencing a weird issue in a deployment of an haproxy with dockercloud (AWS).

![image](https://cloud.githubusercontent.com/assets/3540825/16713972/d1f46eba-46be-11e6-8d39-d41c61e48c44.png)

It seems that every time after a deploy and randomly after redeploy of service I get a Bad Gateway - A second refresh will almost always work. This is a very strange behavior.

Not sure which information to share to shed some light on the source of this issue.

```
test-proxy:
  environment:
    - EXTRA_GLOBAL_SETTINGS=debug
    - FORCE_SSL=yes
    - "SSL_CERT=<CERT>
  image: 'ilaif/my_haproxy:staging'
  links:
    - api-gateway
  ports:
    - '80:80'
    - '443:443'
    - '1936:1936'
  restart: always
  roles:
    - global
```

Where api-gateway is a node-http-proxy which has some logic to further reroute requests to other services.

The same installation without the haproxy works just fine so I'm assuming the problem is with haproxy.

Thanks in advance,
Ilai
