### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by jake-low** [docker/dockercloud-haproxy#97]
Perplexed by this; it's a very minimal config. Running in Docker Cloud

stack "edge":

```
proxy:
  image: dockercloud/haproxy
  links:
    - webserver.foo-dot-com:foo
    - webserver.bar-dot-com:bar
  ports:
    - 80:80
  roles:
    - global
```

stack "foo-dot-com"

```
webserver:
  image: # an image I wrote; listens on 80
  environment:
    - VIRTUAL_HOST=foo.example.com # "foo" subdomain on a domain I own
```

stack "bar-dot-com":

```
webserver:
  image: # another image I wrote; listens on 80
  environment:
    - VIRTUAL_HOST=bar.example.com # "bar" subdomain on a domain I own
```

`dig` shows that the CNAME entries for `foo.example.com` and `bar.example.com` point to `proxy.edge.<hash>.svc.dockerapp.io`.

`docker-cloud exec foo curl localhost` works, and same for bar.

`docker-cloud exec proxy curl foo` works, and also for bar.

Clearly, the backend containers are working.

I read the instructions carefully and I don't _think_ I'm misconfiguring.

There's nothing (apart from the config output) in the HAProxy logs, even when I add `EXTRA_GLOBAL_SETTINGS=debug`. The only hint that something goes wrong is that `Errors/Conn` increments in the statistics report page every time I `curl foo.example.com` from my machine.

And, of course, finally, `curl foo.example.com` returns `503 Service Unavailable`.
